/* eslint-disable */
define({
    "properties": [{
        "name": "enable",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "true",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "filterConfiguration",
        "dataType": "Property",
        "type": "String",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "format",
        "dataType": "Property",
        "type": "String",
        "value0": "F",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "headerHeight",
        "dataType": "Property",
        "type": "UInteger",
        "value0": "40",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "imageAcknowledged",
        "dataType": "Property",
        "type": "ImagePath",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "imageActive",
        "dataType": "Property",
        "type": "ImagePath",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "imageInactive",
        "dataType": "Property",
        "type": "ImagePath",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "imageUnacknowledged",
        "dataType": "Property",
        "type": "ImagePath",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "itemsPerPage",
        "dataType": "Property",
        "type": "Integer",
        "value0": "3",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "mpLink",
        "dataType": "Property",
        "type": "MpComIdentType",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "nextText",
        "dataType": "Property",
        "type": "String",
        "value0": "Next",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "paging",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "true",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "permissionOperate",
        "dataType": "Property",
        "type": "RoleCollection",
        "value0": "addValue0Here",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "permissionView",
        "dataType": "Property",
        "type": "RoleCollection",
        "value0": "addValue0Here",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "previousText",
        "dataType": "Property",
        "type": "String",
        "value0": "Previous",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "searchBox",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "true",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "sortConfiguration",
        "dataType": "Property",
        "type": "String",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "style",
        "dataType": "Property",
        "type": "StyleReference",
        "value0": "default",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "styleConfiguration",
        "dataType": "Property",
        "type": "String",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "visible",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "true",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "columnType",
        "dataType": "Property",
        "type": "brease.enum.AlarmHistoryItemType",
        "value0": "message",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "text",
        "dataType": "Property",
        "type": "String",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "imageActiveAcknowledged",
        "dataType": "Property",
        "type": "ImagePath",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "columnType",
        "dataType": "Property",
        "type": "brease.enum.AlarmListItemType",
        "value0": "message",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "columnType",
        "dataType": "Property",
        "type": "brease.enum.AuditListItemType",
        "value0": "text",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "barPadding",
        "dataType": "Property",
        "type": "Integer",
        "value0": "5",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "chartMargin",
        "dataType": "Property",
        "type": "PixelValCollection",
        "value0": "30px 30px 0px 0px",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "format",
        "dataType": "Property",
        "type": "brease.config.MeasurementSystemFormat",
        "value0": "{'metric':{ 'decimalPlaces' : 0, 'minimumIntegerDigits' : 1 }, 'imperial' :{ 'decimalPlaces' : 0, 'minimumIntegerDigits' : 1 }, 'imperial-us' :{ 'decimalPlaces' : 0, 'minimumIntegerDigits' : 1 }}",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "orientation",
        "dataType": "Property",
        "type": "brease.enum.Orientation",
        "value0": "BottomToTop",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "showUnit",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "false",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "showValue",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "true",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "transitionTime",
        "dataType": "Property",
        "type": "UInteger",
        "value0": "0",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "unit",
        "dataType": "Property",
        "type": "brease.config.MeasurementSystemUnit",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "xAxisHeight",
        "dataType": "Property",
        "type": "Integer",
        "value0": "40",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "yAxisWidth",
        "dataType": "Property",
        "type": "Integer",
        "value0": "40",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "maxValue",
        "dataType": "Property",
        "type": "Number",
        "value0": "100",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "minValue",
        "dataType": "Property",
        "type": "Number",
        "value0": "0",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "node",
        "dataType": "Property",
        "type": "brease.datatype.Node",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "value",
        "dataType": "Property",
        "type": "Number",
        "value0": "50",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "window",
        "dataType": "Property",
        "type": "Number",
        "value0": "0",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "windowNode",
        "dataType": "Property",
        "type": "brease.datatype.Node",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "changeOnMove",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "true",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "image",
        "dataType": "Property",
        "type": "ImagePath",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "largeChange",
        "dataType": "Property",
        "type": "UNumber",
        "value0": "10",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "majorTicks",
        "dataType": "Property",
        "type": "UInteger",
        "value0": "5",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "scaleOffset",
        "dataType": "Property",
        "type": "PixelVal",
        "value0": "15px",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "showTickNumbers",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "false",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "showValueDisplay",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "false",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "smallChange",
        "dataType": "Property",
        "type": "UNumber",
        "value0": "1",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "thumbSize",
        "dataType": "Property",
        "type": "PixelVal",
        "value0": "25px",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "tickPosition",
        "dataType": "Property",
        "type": "brease.enum.TickStyle",
        "value0": "none",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "trackSize",
        "dataType": "Property",
        "type": "PixelVal",
        "value0": "7px",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "valueDisplaySize",
        "dataType": "Property",
        "type": "PixelVal",
        "value0": "35px",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "breakWord",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "false",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "ellipsis",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "false",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "imageAlign",
        "dataType": "Property",
        "type": "brease.enum.ImageAlign",
        "value0": "left",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "mouseDownImage",
        "dataType": "Property",
        "type": "ImagePath",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "mouseDownText",
        "dataType": "Property",
        "type": "String",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "multiLine",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "false",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "wordWrap",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "false",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "alignment",
        "dataType": "Property",
        "type": "brease.enum.Direction",
        "value0": "vertical",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "autoScroll",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "false",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "childPositioning",
        "dataType": "Property",
        "type": "brease.enum.ChildPositioning",
        "value0": "absolute",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "selectedIndex",
        "dataType": "Property",
        "type": "Integer",
        "value0": "0",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "infiniteScroll",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "true",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "maxZoomLevel",
        "dataType": "Property",
        "type": "UInteger",
        "value0": "500",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "minZoomLevel",
        "dataType": "Property",
        "type": "UInteger",
        "value0": "20",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "showGrid",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "true",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "zoomType",
        "dataType": "Property",
        "type": "brease.enum.ChartZoomType",
        "value0": "xy",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "xAxisRefId",
        "dataType": "Property",
        "type": "String",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "axisLabel",
        "dataType": "Property",
        "type": "String",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "axisLabelDistance",
        "dataType": "Property",
        "type": "PixelVal",
        "value0": "30px",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "axisPosition",
        "dataType": "Property",
        "type": "brease.enum.VerticalAlign",
        "value0": "bottom",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "tickLabelDistance",
        "dataType": "Property",
        "type": "PixelVal",
        "value0": "9px",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "tickLabelRotation",
        "dataType": "Property",
        "type": "Rotation",
        "value0": "0deg",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "axisPosition",
        "dataType": "Property",
        "type": "brease.enum.HorizontalAlign",
        "value0": "left",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "interpolationType",
        "dataType": "Property",
        "type": "brease.enum.ChartInterpolationType",
        "value0": "linear",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "numberOfSamples",
        "dataType": "Property",
        "type": "Integer",
        "value0": "-1",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "boxSize",
        "dataType": "Property",
        "type": "Integer",
        "value0": "25",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "checkedBoxImage",
        "dataType": "Property",
        "type": "ImagePath",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "disabledCheckedBoxImage",
        "dataType": "Property",
        "type": "ImagePath",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "disabledUncheckedBoxImage",
        "dataType": "Property",
        "type": "ImagePath",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "uncheckedBoxImage",
        "dataType": "Property",
        "type": "ImagePath",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "value",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "false",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "pickerPosition",
        "dataType": "Property",
        "type": "brease.enum.Position",
        "value0": "right",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "submitOnChange",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "true",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "value",
        "dataType": "Property",
        "type": "DateTime",
        "value0": "1970-01-01T00:00:00.000Z",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "cropToParent",
        "dataType": "Property",
        "type": "brease.enum.CropToParent",
        "value0": "none",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "dataProvider",
        "dataType": "Property",
        "type": "ItemCollection",
        "value0": "addValue0Here",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "fitHeight2Items",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "true",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "imageAlign",
        "dataType": "Property",
        "type": "brease.enum.ImagePosition",
        "value0": "left",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "imagePath",
        "dataType": "Property",
        "type": "DirectoryPath",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "itemHeight",
        "dataType": "Property",
        "type": "Integer",
        "value0": "40",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "listPosition",
        "dataType": "Property",
        "type": "brease.enum.Position",
        "value0": "right",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "listWidth",
        "dataType": "Property",
        "type": "Integer",
        "value0": "150",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "maxVisibleEntries",
        "dataType": "Property",
        "type": "UInteger",
        "value0": "4",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "selectedValue",
        "dataType": "Property",
        "type": "String",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "boxConfiguration",
        "dataType": "Property",
        "type": "String",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "columnCount",
        "dataType": "Property",
        "type": "UInteger",
        "value0": "4",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "rowCount",
        "dataType": "Property",
        "type": "UInteger",
        "value0": "4",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "labelStyle",
        "dataType": "Property",
        "type": "StyleReference",
        "value0": "default",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "nodeIn",
        "dataType": "Property",
        "type": "brease.datatype.Node",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "nodeOut",
        "dataType": "Property",
        "type": "brease.datatype.Node",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "numericInputStyle",
        "dataType": "Property",
        "type": "StyleReference",
        "value0": "default",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "numericOutputStyle",
        "dataType": "Property",
        "type": "StyleReference",
        "value0": "default",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "valueIn",
        "dataType": "Property",
        "type": "Number",
        "value0": "0",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "valueOut",
        "dataType": "Property",
        "type": "Number",
        "value0": "0",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "float",
        "dataType": "Property",
        "type": "brease.enum.Floating",
        "value0": "left",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "autoClose",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "false",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "buttonOffset",
        "dataType": "Property",
        "type": "Integer",
        "value0": "0",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "buttonStyle",
        "dataType": "Property",
        "type": "StyleReference",
        "value0": "default",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "docking",
        "dataType": "Property",
        "type": "brease.enum.ImageAlign",
        "value0": "left",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "mode",
        "dataType": "Property",
        "type": "brease.enum.DialogMode",
        "value0": "modeless",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "showButton",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "true",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "showOnTop",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "false",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "modal",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "true",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "position",
        "dataType": "Property",
        "type": "Object",
        "value0": "{'horizontal':'center', 'vertical':'middle'}",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "maxHeight",
        "dataType": "Property",
        "type": "Integer",
        "value0": "0",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "sizeMode",
        "dataType": "Property",
        "type": "brease.enum.SizeMode",
        "value0": "contain",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "imageAlign",
        "dataType": "Property",
        "type": "brease.enum.BackgroundPosition",
        "value0": "center center",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "imageList",
        "dataType": "Property",
        "type": "GraphicCollection",
        "value0": "addValue0Here",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "imagePrefix",
        "dataType": "Property",
        "type": "DirectoryPath",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "columnWidth",
        "dataType": "Property",
        "type": "UInteger",
        "value0": "90",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "keyboard",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "true",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "maxColumns",
        "dataType": "Property",
        "type": "UInteger",
        "value0": "0",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "maxRows",
        "dataType": "Property",
        "type": "UInteger",
        "value0": "0",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "minColumns",
        "dataType": "Property",
        "type": "UInteger",
        "value0": "4",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "rowHeight",
        "dataType": "Property",
        "type": "UInteger",
        "value0": "90",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "showComments",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "true",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "showTitleBar",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "true",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "displaySettings",
        "dataType": "Property",
        "type": "brease.enum.DropDownDisplaySettings",
        "value0": "default",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "x1",
        "dataType": "Property",
        "type": "Integer",
        "value0": "addValue0Here",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "x2",
        "dataType": "Property",
        "type": "Integer",
        "value0": "addValue0Here",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "y1",
        "dataType": "Property",
        "type": "Integer",
        "value0": "addValue0Here",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "y2",
        "dataType": "Property",
        "type": "Integer",
        "value0": "addValue0Here",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "areasPadding",
        "dataType": "Property",
        "type": "UInteger",
        "value0": "3",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "areasSize",
        "dataType": "Property",
        "type": "UInteger",
        "value0": "10",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "minorTicks",
        "dataType": "Property",
        "type": "UInteger",
        "value0": "4",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "pointerPadding",
        "dataType": "Property",
        "type": "UInteger",
        "value0": "0",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "pointerSize",
        "dataType": "Property",
        "type": "UInteger",
        "value0": "15",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "scaleArea0",
        "dataType": "Property",
        "type": "Number",
        "value0": "0",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "scaleArea0Node",
        "dataType": "Property",
        "type": "brease.datatype.Node",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "scaleArea1",
        "dataType": "Property",
        "type": "Number",
        "value0": "20",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "scaleArea1Node",
        "dataType": "Property",
        "type": "brease.datatype.Node",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "scaleArea2",
        "dataType": "Property",
        "type": "Number",
        "value0": "40",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "scaleArea2Node",
        "dataType": "Property",
        "type": "brease.datatype.Node",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "scaleArea3",
        "dataType": "Property",
        "type": "Number",
        "value0": "60",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "scaleArea3Node",
        "dataType": "Property",
        "type": "brease.datatype.Node",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "scaleArea4",
        "dataType": "Property",
        "type": "Number",
        "value0": "80",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "scaleArea4Node",
        "dataType": "Property",
        "type": "brease.datatype.Node",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "scaleArea5",
        "dataType": "Property",
        "type": "Number",
        "value0": "100",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "scaleArea5Node",
        "dataType": "Property",
        "type": "brease.datatype.Node",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "showPointer",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "true",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "cursorNode",
        "dataType": "Property",
        "type": "brease.datatype.Node",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "cursorValue",
        "dataType": "Property",
        "type": "Number",
        "value0": "0",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "node",
        "dataType": "Property",
        "type": "brease.datatype.ArrayNode",
        "value0": "addValue0Here",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "value",
        "dataType": "Property",
        "type": "NumberArray1D",
        "value0": "addValue0Here",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "minValue",
        "dataType": "Property",
        "type": "UInteger",
        "value0": "0",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "maxValue",
        "dataType": "Property",
        "type": "DateTime",
        "value0": "1970-01-01T00:01:00.000Z",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "minValue",
        "dataType": "Property",
        "type": "DateTime",
        "value0": "1970-01-01T00:00:00.000Z",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "value",
        "dataType": "Property",
        "type": "UInteger",
        "value0": "0",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "value",
        "dataType": "Property",
        "type": "Time",
        "value0": "0",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "selectedIndex",
        "dataType": "Property",
        "type": "UInteger",
        "value0": "0",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "autFailMessage",
        "dataType": "Property",
        "type": "String",
        "value0": "Authorisation failed",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "buttonLabel",
        "dataType": "Property",
        "type": "String",
        "value0": "Login",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "enableUserInput",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "true",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "messageStyle",
        "dataType": "Property",
        "type": "StyleReference",
        "value0": "default",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "passwordInputStyle",
        "dataType": "Property",
        "type": "StyleReference",
        "value0": "default",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "passwordLabel",
        "dataType": "Property",
        "type": "String",
        "value0": "Password",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "setUserFailMessage",
        "dataType": "Property",
        "type": "String",
        "value0": "Set User failed",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "setUserSuccessMessage",
        "dataType": "Property",
        "type": "String",
        "value0": "Login successful",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "userChangedMessage",
        "dataType": "Property",
        "type": "String",
        "value0": "User changed to: ",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "userInputStyle",
        "dataType": "Property",
        "type": "StyleReference",
        "value0": "default",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "userLabel",
        "dataType": "Property",
        "type": "String",
        "value0": "Username",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "userName",
        "dataType": "Property",
        "type": "String",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "password",
        "dataType": "Property",
        "type": "String",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "value",
        "dataType": "Property",
        "type": "Integer",
        "value0": "0",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "buttonHeight",
        "dataType": "Property",
        "type": "Integer",
        "value0": "30",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "buttonImageAlign",
        "dataType": "Property",
        "type": "brease.enum.ImageAlign",
        "value0": "left",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "buttonWidth",
        "dataType": "Property",
        "type": "Integer",
        "value0": "100",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "navRefId",
        "dataType": "Property",
        "type": "NavigationReference",
        "value0": "addValue0Here",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "isToggle",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "true",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "pageId",
        "dataType": "Property",
        "type": "PageReference",
        "value0": "addValue0Here",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "limitViolationPolicy",
        "dataType": "Property",
        "type": "brease.enum.LimitViolationPolicy",
        "value0": "noSubmit",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "numPadStyle",
        "dataType": "Property",
        "type": "StyleReference",
        "value0": "default",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "numpadPosition",
        "dataType": "Property",
        "type": "brease.enum.Position",
        "value0": "right",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "unitAlign",
        "dataType": "Property",
        "type": "brease.enum.ImageAlign",
        "value0": "left",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "unitWidth",
        "dataType": "Property",
        "type": "Size",
        "value0": "0",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "useDigitGrouping",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "true",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "autoscale",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "false",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "timeSpan",
        "dataType": "Property",
        "type": "Integer",
        "value0": "60",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "colorList",
        "dataType": "Property",
        "type": "ColorList",
        "value0": "#FFCC66,#FF8800,#FFCC99,#993333",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "maxZoomLevel",
        "dataType": "Property",
        "type": "UNumber",
        "value0": "500",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "minZoomLevel",
        "dataType": "Property",
        "type": "UNumber",
        "value0": "20",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "svgContent",
        "dataType": "Property",
        "type": "String",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "svgFilePath",
        "dataType": "Property",
        "type": "ImagePath",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "transform",
        "dataType": "Property",
        "type": "String",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "inputRestriction",
        "dataType": "Property",
        "type": "RegEx",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "maxLength",
        "dataType": "Property",
        "type": "Integer",
        "value0": "-1",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "placeholder",
        "dataType": "Property",
        "type": "String",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "value",
        "dataType": "Property",
        "type": "String",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "documentZoom",
        "dataType": "Property",
        "type": "String",
        "value0": "auto",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "showToolbar",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "false",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "src",
        "dataType": "Property",
        "type": "String",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "startPage",
        "dataType": "Property",
        "type": "UNumber",
        "value0": "0",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "usePlugin",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "true",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "infoBox",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "true",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "itemPadding",
        "dataType": "Property",
        "type": "UInteger",
        "value0": "2",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "showData",
        "dataType": "Property",
        "type": "brease.enum.ShowData",
        "value0": "percentage",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "xAxisItemId",
        "dataType": "Property",
        "type": "String",
        "value0": "addValue0Here",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "barAnimation",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "false",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "labelPosition",
        "dataType": "Property",
        "type": "brease.enum.Position",
        "value0": "right",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "labelSize",
        "dataType": "Property",
        "type": "Size",
        "value0": "30",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "showLabel",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "true",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "stripedProgressBar",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "false",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "buttonPadding",
        "dataType": "Property",
        "type": "UInteger",
        "value0": "45",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "radius",
        "dataType": "Property",
        "type": "PixelVal",
        "value0": "120px",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "range",
        "dataType": "Property",
        "type": "UNumber",
        "value0": "180",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "snapToPosition",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "false",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "startAngle",
        "dataType": "Property",
        "type": "UNumber",
        "value0": "270",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "scaleArea0",
        "dataType": "Property",
        "type": "Integer",
        "value0": "0",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "scaleArea1",
        "dataType": "Property",
        "type": "Integer",
        "value0": "20",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "scaleArea2",
        "dataType": "Property",
        "type": "Integer",
        "value0": "40",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "scaleArea3",
        "dataType": "Property",
        "type": "Integer",
        "value0": "60",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "scaleArea4",
        "dataType": "Property",
        "type": "Integer",
        "value0": "80",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "scaleArea5",
        "dataType": "Property",
        "type": "Integer",
        "value0": "100",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "scaleAreaInPercent",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "true",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "enableDragAndDrop",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "false",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "imageSuffix",
        "dataType": "Property",
        "type": "ImageType",
        "value0": ".png",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "selectedCommandName",
        "dataType": "Property",
        "type": "String",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "selectedHierarchy",
        "dataType": "Property",
        "type": "String",
        "value0": "addValue0Here",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "stepItemStyle",
        "dataType": "Property",
        "type": "StepItemStyleReferenceCollection",
        "value0": "[]",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "numberOfSelectedStepItems",
        "dataType": "Property",
        "type": "UInteger",
        "value0": "0",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "selectedStepItem",
        "dataType": "Property",
        "type": "String",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "columnWidth",
        "dataType": "Property",
        "type": "Size",
        "value0": "100",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "dataOrientation",
        "dataType": "Property",
        "type": "brease.enum.Direction",
        "value0": "vertical",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "offsetColumn",
        "dataType": "Property",
        "type": "Integer",
        "value0": "0",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "offsetRow",
        "dataType": "Property",
        "type": "Integer",
        "value0": "0",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "rowHeight",
        "dataType": "Property",
        "type": "Size",
        "value0": "30",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "scrollLinkXRefId",
        "dataType": "Property",
        "type": "String",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "scrollLinkYRefId",
        "dataType": "Property",
        "type": "String",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "selectedColumn",
        "dataType": "Property",
        "type": "Integer",
        "value0": "0",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "selectedRow",
        "dataType": "Property",
        "type": "Integer",
        "value0": "0",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "selection",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "true",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "showHeader",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "true",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "showScrollbars",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "true",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "showSortingButton",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "false",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "tableConfiguration",
        "dataType": "Property",
        "type": "String",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "selectedImageIndex",
        "dataType": "Property",
        "type": "Integer",
        "value0": "0",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "selectedIndex",
        "dataType": "Property",
        "type": "NumberArray1D",
        "value0": "addValue0Here",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "tabPosition",
        "dataType": "Property",
        "type": "brease.enum.TabPosition",
        "value0": "top",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "useTableStyling",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "true",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "columnType",
        "dataType": "Property",
        "type": "String",
        "value0": "timestamp",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "input",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "false",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "inputStyle",
        "dataType": "Property",
        "type": "String",
        "value0": "default",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "stringValue",
        "dataType": "Property",
        "type": "StringArray1D",
        "value0": "addValue0Here",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "itemAlign",
        "dataType": "Property",
        "type": "brease.enum.HorizontalPosition",
        "value0": "center",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "itemHeight",
        "dataType": "Property",
        "type": "PixelVal",
        "value0": "40px",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "itemPadding",
        "dataType": "Property",
        "type": "PixelVal",
        "value0": "10px",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "maxItemWidth",
        "dataType": "Property",
        "type": "UInteger",
        "value0": "100",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "minItemWidth",
        "dataType": "Property",
        "type": "UInteger",
        "value0": "50",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "padding",
        "dataType": "Property",
        "type": "Padding",
        "value0": "10px",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "textAlign",
        "dataType": "Property",
        "type": "brease.enum.TextAlign",
        "value0": "center",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "data",
        "dataType": "Property",
        "type": "String",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "durationLabel",
        "dataType": "Property",
        "type": "String",
        "value0": "Duration: ",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "endLabel",
        "dataType": "Property",
        "type": "String",
        "value0": "End: ",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "infoLabel",
        "dataType": "Property",
        "type": "String",
        "value0": "Info: ",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "scalePadding",
        "dataType": "Property",
        "type": "UInteger",
        "value0": "30",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "showInfoBoxDuration",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "false",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "showInfoBoxEndTime",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "true",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "showInfoBoxInfo",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "true",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "showInfoBoxStartTime",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "true",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "showScale",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "true",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "startLabel",
        "dataType": "Property",
        "type": "String",
        "value0": "Start: ",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "startTime",
        "dataType": "Property",
        "type": "DateTime",
        "value0": "1970-01-01T00:00:00.000Z",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "autoplay",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "false",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "controls",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "true",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "loop",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "false",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "muted",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "false",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "poster",
        "dataType": "Property",
        "type": "ImagePath",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "preload",
        "dataType": "Property",
        "type": "brease.enum.VideoPlayerPreload",
        "value0": "none",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "autoConnect",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "true",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "controlBarHeight",
        "dataType": "Property",
        "type": "Size",
        "value0": "50",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "host",
        "dataType": "Property",
        "type": "String",
        "value0": "localhost",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "port",
        "dataType": "Property",
        "type": "UInteger",
        "value0": "5900",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "showControlBar",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "true",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "busy",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "false",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "path",
        "dataType": "Property",
        "type": "String",
        "value0": "sdm",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "port",
        "dataType": "Property",
        "type": "Number",
        "value0": "80",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "query",
        "dataType": "Property",
        "type": "String",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "useURL",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "true",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "buttonDistance",
        "dataType": "Property",
        "type": "UInteger",
        "value0": "30",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "range",
        "dataType": "Property",
        "type": "UInteger",
        "value0": "170",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "order",
        "dataType": "Property",
        "type": "String",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "rearrChildren",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "false",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "arguments",
        "dataType": "Property",
        "type": "String",
        "value0": "addValue0Here",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "call",
        "dataType": "Property",
        "type": "Boolean",
        "value0": "false",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "methodId",
        "dataType": "Property",
        "type": "String",
        "value0": "addValue0Here",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "objectId",
        "dataType": "Property",
        "type": "String",
        "value0": "addValue0Here",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "fileDeviceName",
        "dataType": "Property",
        "type": "String",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "fileName",
        "dataType": "Property",
        "type": "String",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "filePath",
        "dataType": "Property",
        "type": "String",
        "value0": "",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "endTime",
        "dataType": "Property",
        "type": "Number",
        "value0": "10",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "nodeIdsValues",
        "dataType": "Property",
        "type": "StringArray1D",
        "value0": "addValue0Here",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "startTime",
        "dataType": "Property",
        "type": "Number",
        "value0": "0",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "triggerTime",
        "dataType": "Property",
        "type": "Number",
        "value0": "0",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "timeFrame",
        "dataType": "Property",
        "type": "String",
        "value0": "relative",
        "value1": "addValue1Here",
        "value2": ""
    }, {
        "name": "timeValuesRefId",
        "dataType": "Property",
        "type": "String",
        "value0": "addValue0Here",
        "value1": "addValue1Here",
        "value2": ""
    }]
});
